apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      adminPassword: admin
      service:
        type: NodePort
        nodePort: 30000
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
