apiVersion: v1
kind: Secret
metadata:
    name: test-secret
type: Opaque
data:
    #ENC[AES256_GCM,data:CYY4Qc8w7Ns=,iv:viCfbM2Jj98fB4gLMv2FaZad5d5iM+IFzUWlg5B9MkY=,tag:NGr6B3iFHXToNr3dKD9wOg==,type:comment]
    username: ENC[AES256_GCM,data:Z8SUkS2DjSI=,iv:1/msWzBvorRgnEyYiNe1DNY291UY2v5agqzAsHX3wRo=,tag:SO7OsekehV+XLzTwV0flCg==,type:str]
    #ENC[AES256_GCM,data:MJF/Bx6+zrLCk6YyXaqK,iv:NB/+g1EmxMREk2LZ3qTwkLX45VGCdk2/fzUuqhsFhsQ=,tag:d6J3lhx5OVgGYPTizfbdog==,type:comment]
    password: ENC[AES256_GCM,data:kf5vO7DmpkCAArAPeQkgLg==,iv:YtARaf/GWNrzeIg7p0Wyrl+SJlAtEU+5SV4iZ7wD44M=,tag:8IlbL5H+J9eYnrr0cUIfMA==,type:str]
sops:
    age:
        - recipient: age1w9g65zjvl0k3ezkvuq9xwggmqcry6nvkrpdpeqke8znxk7e9kfzs899uyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVXFsQ0d4UThMODZhMVJh
            cUZZeVpLRTkxQXpHcE5TaWQxR3BlVUdGandFCkNnL3JwWkY3SFFIaURlOStrcFpy
            UjV0Q2NOU2l2WnVKaVhWZmUzL2ZWOU0KLS0tIERhY2hoTG8yQlhiTEViT2R6NTJp
            azBmei84bUVaMkNEdkIzd3JhUDl2NXcKrQmh2U+LGQ3lFyN2X/aGRRosJp/wEPR9
            YhIyYcBx5IlSe8YxaV/zn6SqdaRTtLGULzkO6twesz4++MbPI50NwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T11:05:03Z"
    mac: ENC[AES256_GCM,data:K2sHVgcO3Yuj/BxHDJPbC79pag3cFCiefmsKd0lPpdDSMNxfYaMvkj5OAhpeMKcSw7li4zBmOmMFn2gmLnz9TM6mkdzLjmErm7Y0u5wxEA1bowvRiM5bxYmt0D5GF06szsPqqWeTJ5rgr2sprXRYIOjVEmBwj7XGcEW3SwdFcAQ=,iv:peF6w+swh0KmFxYZI6BVCcerGbHo+OpZ/EeFlCjwVqU=,tag:huMuO2Ub2kHRfcVhcakdsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
